sudo: required
cache:
  timeout: 10000
  directories:
  - ${PWD}/.m2

services:
  - docker

# We test against all influxdb versions with the most actual JDK.
# Test only the most recent influxdb version with JDK8 which will be legacy soon.
env:
  - MAVEN_JAVA_VERSION=3-jdk-10-slim INFLUXDB_VERSION=1.6
  - MAVEN_JAVA_VERSION=3-jdk-10-slim INFLUXDB_VERSION=1.5
  - MAVEN_JAVA_VERSION=3-jdk-10-slim INFLUXDB_VERSION=1.4
  - MAVEN_JAVA_VERSION=3-jdk-10-slim INFLUXDB_VERSION=1.3
  - MAVEN_JAVA_VERSION=3-jdk-10-slim INFLUXDB_VERSION=1.2
  - MAVEN_JAVA_VERSION=3-jdk-10-slim INFLUXDB_VERSION=1.1
  - MAVEN_JAVA_VERSION=3-jdk-8-slim INFLUXDB_VERSION=1.6

script: ./compile-and-test.sh

jobs:
  include:
  - stage: deploy
    script: docker run -it --rm --volume ${PWD}:/usr/src/mymaven --volume ${PWD}/.m2:/root/.m2 --workdir /usr/src/mymaven maven:${MAVEN_JAVA_VERSION} mvn clean deploy -DskipTests -s config/deploy-settings.xml -U -Denv.BONITOO_SNAPSHOT_USER=${BONITOO_SNAPSHOT_USER} -Denv.BONITOO_SNAPSHOT_PASSWORD=${BONITOO_SNAPSHOT_PASSWORD}
    env: MAVEN_JAVA_VERSION=3-jdk-8-slim INFLUXDB_VERSION=1.6

after_success:
  - echo $TRAVIS_BUILD_STAGE_NAME
  - if [ "$TRAVIS_BUILD_STAGE_NAME" == "Test" ] && [ "$MAVEN_JAVA_VERSION" == "3-jdk-8-slim" ]; then
      bash <(curl -s https://codecov.io/bash)
    fi

after_failure:
  - cat target/surefire-reports/*.txt
