#
# The MIT License
# Copyright © 2018
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.
#

version: 2

cache-key: &cache-key v4-dependencies-{{ checksum "pom.xml" }}
maven-opts: &maven-opts -Xmx3200m

DEFAULT_INFLUXDB_VERSION: &DEFAULT_INFLUXDB_VERSION 1.6

aliases:
  startInfluxDB: &startInfluxDB
    name: Start InfluxDB
    command: |
      docker kill influxdb || true
      docker rm influxdb || true
      docker pull influxdb:${INFLUXDB_VERSION}-alpine || true
      docker run --detach --name influxdb --publish 8086:8086 --publish 8089:8089/udp --volume ${PWD}/config/influxdb.conf:/etc/influxdb/influxdb.conf influxdb:${INFLUXDB_VERSION}-alpine

shared: &shared
  working_directory: ~/repo

  environment:
    MAVEN_OPTS: *maven-opts

  steps:
  - checkout
  - restore_cache:
      keys:
      - *cache-key
  - run: *startInfluxDB
  - run:
      name: Test
      command: mvn clean install -U

jobs:

  JDK_LTS:
    <<: *shared
    machine:
      enabled: true
    environment:
      INFLUXDB_VERSION: *DEFAULT_INFLUXDB_VERSION

  Influx_DB1.6:
    <<: *shared
    machine:
      enabled: true
    environment:
      INFLUXDB_VERSION: *DEFAULT_INFLUXDB_VERSION

  Influx_DB1.5:
    <<: *shared
    machine:
      enabled: true
    environment:
      INFLUXDB_VERSION: 1.5

  Influx_DB1.4:
    <<: *shared
    machine:
      enabled: true
    environment:
      INFLUXDB_VERSION: 1.4

  Influx_DB1.3:
    <<: *shared
    machine:
      enabled: true
    environment:
      INFLUXDB_VERSION: 1.3

  Influx_DB1.2:
    <<: *shared
    machine:
      enabled: true
    environment:
      INFLUXDB_VERSION: 1.2

  Influx_DB1.1:
    <<: *shared
    machine:
      enabled: true
    environment:
      INFLUXDB_VERSION: 1.1

  code_coverage:
    machine:
      enabled: true

    working_directory: ~/repo

    environment:
      MAVEN_OPTS: *maven-opts
      INFLUXDB_VERSION: *DEFAULT_INFLUXDB_VERSION

    steps:
    - checkout

    - restore_cache:
        keys:
        - *cache-key

    - run: *startInfluxDB

    - run:
        name: Create Code Coverage test report
        command: mvn clean install -U

    - run:
        name: Report Code Coverage to CodeCov
        command: bash <(curl -s https://codecov.io/bash)

  deploy:
    machine:
      enabled: true

    working_directory: ~/repo

    environment:
      MAVEN_OPTS: *maven-opts
      INFLUXDB_VERSION: *DEFAULT_INFLUXDB_VERSION

    steps:
    - checkout

    - restore_cache:
        keys:
        - *cache-key

    - run: *startInfluxDB

    - run:
        name: Build & Deploy
        command: mvn clean deploy -s config/deploy-settings.xml -U

    - save_cache:
        paths:
        - ~/.m2
        key: *cache-key

workflows:
  version: 2
  build:
    jobs:
    - JDK_LTS
    - Influx_DB1.6
    - Influx_DB1.5
    - Influx_DB1.4
    - Influx_DB1.3
    - Influx_DB1.2
    - Influx_DB1.1
    - code_coverage:
        requires:
          - JDK_LTS
          - Influx_DB1.6
          - Influx_DB1.5
          - Influx_DB1.4
          - Influx_DB1.3
          - Influx_DB1.2
          - Influx_DB1.1
    - deploy:
        requires:
          - JDK_LTS
          - Influx_DB1.6
          - Influx_DB1.5
          - Influx_DB1.4
          - Influx_DB1.3
          - Influx_DB1.2
          - Influx_DB1.1